### ISSUE TITLE
AdminMainActivity

### ISSUE THREAD

**Issue by sheagallagher** [ethanbleier/Movie-App#6]
### Components
Recycler View:
- [x] usersList

Buttons:
- [x] signOut -> LoginActivity
- [x] addNewUser -> AdminEditUserActivity

### TODO
- [ ] Sign out
- [ ] Add list of users (clickable)
- [ ] Clicking a user navigates to the AdminEditUserActivity
- [ ] addNewUser button navigates to AdminEditUserActivity
