### ISSUE TITLE
EditMovieActivity

### ISSUE THREAD

**Issue by sheagallagher** [ethanbleier/Movie-App#8]
### Components
Text:

- [x] title
- [x] director
- [x] genre
- [x] year

Buttons
- [x] editMovie -> UpdateMovieActivity
- [x] deleteMovie -> deleteMovie()
- [x] back -> MainActivity || AdminMainActivity()

### TODO

- [ ] implement deleteMovie() method so that is removes movie from database
- [x] when back button is pressed, determine which navigation to make based on the users admin status
- [x] when a user navigates to this activity, the movie information from the movie they clicked on is displayed in the text views
